In [1]:
import numpy as np

0 dimension arry

In [2]:
arr = np.array(20)
print(arr)
print(type(arr))
print(arr.ndim)

20
<class 'numpy.ndarray'>
0


1 d array

In [3]:
arr = np.array([1,2,3,4,5,6,7])
print(arr.ndim)

1


# 2 D array

In [5]:
arr = np.array([[1,2,3],[4,6,7]])
print(arr)
print(arr.ndim)

[[1 2 3]
 [4 6 7]]
2


In [6]:
arr = np.array([[1.1,2.4,3],[4.6,6,7]])
print(arr)
print(arr.ndim)

[[1.1 2.4 3. ]
 [4.6 6.  7. ]]
2


# 3 D array

In [8]:
arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)
print(arr.ndim)
# an array that has 2-D arrays(matrices) as its elements is called 3-D arrays

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3


# creating an array of 5 dimensions and verify that it has 5 dimensions.

In [2]:
import numpy as np
arr = np.array([1,2,3,4,5], ndmin = 5) # we can write like this too
print(arr)
print("numbers of dimensions : ", arr.ndim)

[[[[[1 2 3 4 5]]]]]
numbers of dimensions :  5


## indexing of n dimensions array


In [3]:
arr = np.array([[10,20,30,40,50],[60,70,80,90,100]])
print("first element of 1st row ", arr[0,0])
print("last element of 2nd row ", arr[1,4])
print("sum is ", arr[0,0]+arr[1,4])

first element of 1st row  10
last element of 2nd row  100
sum is  110


## Access 3-D Arrays

In [4]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
# access the 3rd element of the 2nd array of the first array
print(arr[0,1,2])

6


In [5]:
# access 12 from the above array
print(arr[1,1,2])

12


### Slicing of Numpay arrays

### Slicing of 1 D array 

In [12]:
# print(2,3,4) from this array
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
print(arr[1:4])
print(arr[::3]) # from start to end and take 2 steps

[2 3 4]
[ 1  4  7 10 13 16]


### Slicing from 2 D arrays

In [8]:
# print(20,21,22) from this 2 D array
arr = np.array([[10,11,12,13,14,15],[20,21,22,23,24,25]])
print(arr[1,0:3])

[20 21 22]


### Slicing from 3D arrays

In [9]:
arr = np.array([[[1,2,3,4,5],[4,5,6,7,8],[7,8,9,10,11]]])
print(arr[0,1,0:3])


[4 5 6]


# Data types in Numpy

In [ ]:
i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - String
U - unicode String
V - fixed chunk of memory for other type(void)


# checking the data type of an array

In [13]:
arr = np.array([1,2,3,4,5,6])
print(arr.dtype)

int32


In [14]:
arr = np.array(["animas","bat","cat"])
print(arr.dtype)

<U6


## creating arrays with a defined data type

In [15]:
arr = np.array([1,2,3,4,5], dtype = 'S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4' b'5']
|S1


## Numpy array shape

the shape of an array is the number of elements in each dimension

## print the shape of a 2D array

In [18]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)
# output is (2,4) that means it has 2 rows and 4 columns

(2, 4)


In [23]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[11,12,14]]])
print(arr.shape)
# the shape here is defines as (1,3,3) representing
# 2 = 2 rows
# 2 = we have 2 different set of data in each row
# 3 = 3 elements in each set of data

(2, 2, 3)


## joining Numpy arrays

In [25]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
# concatenate function to join arrays
arr = np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


## join 2D arrays

In [33]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
# concatenate function to join arrays
arr = np.concatenate((arr1,arr2),axis=1)
print(arr)
print(arr.ndim)
arr0 = np.concatenate((arr1,arr2),axis=0)
print(arr0)
print(arr0.ndim)

[[1 2 5 6]
 [3 4 7 8]]
2
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
2


## Spliting Numpy Arrays

# spliting the array in 3 parts

In [34]:
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


### spliting the array in 4 parts

In [35]:
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


# Ravel and flatten

## convert multidimensional array into 1D array

In [37]:
# creating a 3 D array to covert into 1D
m = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print("dimension is ", m.ndim)
n = m.ravel()
print(n)
print("dimension is ", n.ndim)
# flatten function is also used to do the same work


dimension is  3
[1 2 3 4 5 6 7 8 9]
dimension is  1


In [40]:
# converting 4D array into 1 D array
c = np.array([[[[1,2,3],[78,89,96],[45,6,7]]]])
print(c)
print(c.ndim)
d = c.ravel()
print(d)
print(d.ndim)

[[[[ 1  2  3]
   [78 89 96]
   [45  6  7]]]]
4
[ 1  2  3 78 89 96 45  6  7]
1


# Unique functions

In [43]:
# unique function is to get unique value from an array and remove the duplicate ones
k = np.array([1,2,3,4,45,6,7,8,96,5,3,3,2,4,5,6,7,8,99,6,6,5])
print(k)
x = np.unique(k)
print(x)
# to get the index number of the values we use
x = np.unique(k, return_index = True)
print(x)


[ 1  2  3  4 45  6  7  8 96  5  3  3  2  4  5  6  7  8 99  6  6  5]
[ 1  2  3  4  5  6  7  8 45 96 99]
(array([ 1,  2,  3,  4,  5,  6,  7,  8, 45, 96, 99]), array([ 0,  1,  2,  3,  9,  5,  6,  7,  4,  8, 18], dtype=int64))


### to check the number of repeated values in an array

In [45]:
k = np.array([1,2,3,4,45,6,7,8,96,5,3,3,2,4,5,6,7,8,99,6,6,5])
print(k)
x = np.unique(k, return_counts = True)
print(x)

[ 1  2  3  4 45  6  7  8 96  5  3  3  2  4  5  6  7  8 99  6  6  5]
(array([ 1,  2,  3,  4,  5,  6,  7,  8, 45, 96, 99]), array([1, 2, 3, 2, 3, 4, 2, 2, 1, 1, 1], dtype=int64))


## Delete

In [46]:
a = np.array([12,13,14,15])
d = np.delete(a,[1])
print(d)

[12 14 15]


## delete from 2 d arrays

In [47]:
x = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(x)
m = np.delete(x, 2,axis = 0)
print()
print(m)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[1 2 3 4]
 [5 6 7 8]]
